repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3   # versión estable de Ruff
    hooks:
      - id: ruff
        name: Ruff Linter
        args: [--fix]   # corrige automáticamente errores de estilo
      - id: ruff-format
        name: Ruff Formatter

  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: pytest
        language: system
        types: [python]